# Generated by Django 5.1.3 on 2024-11-29 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10)])),
                ('author', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
