# Generated by Django 5.1.3 on 2024-11-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
