# Generated by Django 5.1.3 on 2024-11-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_alter_book_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
