# Generated by Django 5.1.3 on 2024-11-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0008_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='slugs',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
