# Generated by Django 5.1.3 on 2024-11-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0009_remove_post_slug_post_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slugs',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
