# Generated by Django 5.1.3 on 2024-11-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0010_alter_post_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slugs',
        ),
    ]
