# Generated by Django 5.1.3 on 2024-11-30 17:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0012_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('author', models.OneToOneField(max_length=25, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='block.users', validators=[django.core.validators.MinLengthValidator(3)])),
                ('content', models.TextField(max_length=1024, validators=[django.core.validators.MinLengthValidator(10)])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
