# Generated by Django 5.1.3 on 2024-11-30 17:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0013_users_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='block.author'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
