# Generated by Django 5.1.3 on 2024-12-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0015_poll_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_poll', to='block.poll')),
                ('votes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to='block.option')),
            ],
        ),
    ]
