# Generated by Django 5.1.3 on 2024-12-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0016_user_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_poll',
            name='votes',
        ),
    ]
